import React, { createContext, useContext, useState } from 'react';

export type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Header
    'nav.home': 'Accueil',
    'nav.formations': 'Formations',
    'nav.pack': 'Pack IoT',
    'nav.contact': 'Contact',
    'nav.contactUs': 'Nous Contacter',
    
    // Hero
    'hero.badge': '🚀 Formations Innovantes en Technologies Avancées',
    'hero.title.ai': 'IA',
    'hero.title.iot': 'IoT',
    'hero.title.automates': 'Automates',
    'hero.title.master': 'Maîtrisez l\'',
    'hero.title.and': ', l\'',
    'hero.title.andThe': 'et les ',
    'hero.description': 'RIOT-SYS vous forme aux technologies industrielles modernes avec des approches pratiques et innovantes, alliant enseignement en ligne et sessions présentielles.',
    'hero.cta.discover': 'Découvrir nos Formations',
    'hero.cta.presentation': 'Voir la Présentation',
    'hero.stats.students': 'Étudiants Formés',
    'hero.stats.satisfaction': 'Taux de Satisfaction',
    'hero.stats.domains': 'Domaines d\'Expertise',
    
    // Formations
    'formations.title': 'Nos Domaines de Formation',
    'formations.subtitle': 'Des formations pratiques et innovantes pour maîtriser les technologies industrielles modernes',
    'formations.ai.title': 'Intelligence Artificielle',
    'formations.ai.description': 'Maîtrisez les algorithmes de machine learning, deep learning et les applications pratiques de l\'IA dans l\'industrie moderne.',
    'formations.iot.title': 'Internet des Objets (IoT)',
    'formations.iot.description': 'Développez des solutions IoT complètes, de la conception des capteurs à l\'analyse des données en temps réel.',
    'formations.automates.title': 'Automates Programmables',
    'formations.automates.description': 'Programmez et configurez des automates industriels connectés pour l\'automatisation avancée des processus.',
    'formations.learnMore': 'En savoir plus',
    'formations.hybrid.title': 'Formation Hybride',
    'formations.hybrid.description': 'Nos formations allient enseignement en ligne et sessions en présentiel, avec un fort accent sur les projets réels et l\'intégration de technologies de pointe.',
    'formations.online': 'Sessions en ligne',
    'formations.onlineDesc': 'Flexibilité et accessibilité',
    'formations.inPerson': 'Sessions présentielles',
    'formations.inPersonDesc': 'Pratique et interaction directe',

    // Page Formations
    'formations.available': 'Formations disponibles',
    'formations.totalHours': 'Heures de formation',
    'formations.satisfaction': 'Taux de satisfaction',
    'formations.popular': 'Populaire',
    'formations.instructor': 'Formateur',
    'formations.features': 'Ce que vous apprendrez',
    'formations.financing': 'Financement disponible',
    'formations.inscription': 'S\'inscrire',
    'formations.noFormations': 'Aucune formation trouvée',
    'formations.noFormationsDesc': 'Aucune formation ne correspond à vos critères de filtrage.',
    'formations.advantages': 'Pourquoi choisir nos formations ?',
    'formations.certification': 'Certification reconnue',
    'formations.certificationDesc': 'Certifications industry reconnues internationalement',
    'formations.support': 'Support personnalisé',
    'formations.supportDesc': 'Accompagnement individualisé par nos experts',
    'formations.flexible': 'Flexibilité totale',
    'formations.flexibleDesc': 'Formation en ligne et présentiel selon vos besoins',
    'formations.projects': 'Projets pratiques',
    'formations.projectsDesc': 'Mise en pratique sur des cas réels d\'entreprise',
    
    // Domaines
    'domains.all': 'Toutes les formations',
    'domains.ai': 'Intelligence Artificielle',
    'domains.iot': 'Internet des Objets',
    'domains.automation': 'Automatisation',
    
    // Pack IoT
    'pack.badge': 'Pack Exclusif',
    'pack.title': 'Pack IoT Smart Starter',
    'pack.subtitle': 'Un ensemble complet d\'outils et de technologies pour maîtriser l\'IoT industriel, l\'IA et les automates programmables dans un environnement connecté.',
    'pack.features.title': 'Technologies Incluses',
    'pack.features.modules': 'Modules Connectés',
    'pack.features.modulesDesc': 'Microcontrôleurs et capteurs de dernière génération',
    'pack.features.ai': 'IA Intégrée',
    'pack.features.aiDesc': 'Systèmes intelligents pour l\'analyse prédictive',
    'pack.features.plc': 'Automates Programmables',
    'pack.features.plcDesc': 'PLCs industriels connectés et configurables',
    'pack.features.connectivity': 'Connectivité Avancée',
    'pack.features.connectivityDesc': 'Wi-Fi, Bluetooth, LoRaWAN, 5G',
    'pack.features.security': 'Sécurité Renforcée',
    'pack.features.securityDesc': 'Chiffrement et authentification robustes',
    'pack.features.dev': 'Environnement de Développement',
    'pack.features.devDesc': 'IDE complet avec simulateurs intégrés',
    'pack.included.title': 'Ce qui est inclus',
    'pack.included.kit': 'Kit de développement IoT complet',
    'pack.included.aiModules': 'Modules IA et machine learning',
    'pack.included.plc': 'Automates programmables industriels',
    'pack.included.cloud': 'Plateforme cloud dédiée',
    'pack.included.docs': 'Documentation technique complète',
    'pack.included.support': 'Support technique 24/7',
    'pack.included.projects': 'Projets pratiques guidés',
    'pack.included.certification': 'Certification officielle',
    'pack.price.complete': 'Pack Complet',
    'pack.cta.order': 'Commander Maintenant',
    'pack.guarantee': 'Garantie satisfait ou remboursé 30 jours',
    'pack.transform.title': 'Prêt à transformer votre avenir ?',
    'pack.transform.subtitle': 'Rejoignez les professionnels qui maîtrisent déjà les technologies de demain',
    'pack.cta.demo': 'Demander une Démo',
    'pack.cta.brochure': 'Télécharger la Brochure',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Discutons de vos besoins en formation et découvrons ensemble comment intégrer nos solutions à vos programmes.',
    'contact.info.title': 'Informations de Contact',
    'contact.phone': 'Téléphone',
    'contact.phoneHours': 'Lun-Ven 9h-18h',
    'contact.email': 'Email',
    'contact.emailResponse': 'Réponse sous 24h',
    'contact.address': 'Adresse',
    'contact.addressNote': 'Formations sur site disponibles',
    'contact.why.title': 'Pourquoi choisir Smart Academy ?',
    'contact.why.experts': 'Expert formateurs certifiés',
    'contact.why.flexible': 'Formations flexibles et adaptées',
    'contact.why.certification': 'Certification reconnue industrie',
    'contact.form.title': 'Demande de Renseignements',
    'contact.form.name': 'Nom complet',
    'contact.form.email': 'Email',
    'contact.form.company': 'Entreprise / Organisation',
    'contact.form.subject': 'Sujet d\'intérêt',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le Message',
    'contact.form.response': 'Nous nous engageons à répondre dans les 24 heures ouvrables.',
    
    // Footer
    'footer.description': 'Centre de formation spécialisé dans l\'Intelligence Artificielle, l\'Internet des Objets et les automates programmables connectés. Nous formons les professionnels de demain aux technologies industrielles modernes.',
    'footer.formations': 'Formations',
    'footer.resources': 'Ressources',
    'footer.documentation': 'Documentation',
    'footer.blog': 'Blog Technique',
    'footer.caseStudies': 'Études de Cas',
    'footer.support': 'Support',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.website': 'Site Web',
    'footer.rights': 'Tous droits réservés.',

    // Inscription
    'inscription.title': 'Finaliser votre inscription',
    'inscription.subtitle': 'Complétez vos informations pour accéder à votre formation',
    'inscription.step.personal': 'Informations Personnelles',
    'inscription.step.professional': 'Informations Professionnelles',
    'inscription.step.pack': 'Choisissez Votre Pack',
    'inscription.step.payment': 'Paiement et Finalisation',
    'inscription.success.title': 'Inscription Confirmée !',
    'inscription.success.message': 'Félicitations ! Votre inscription a été enregistrée avec succès.',
    'inscription.withPack': ' avec le ',
    'inscription.nextSteps': 'Prochaines étapes',
    'inscription.confirmationEmail': 'Email de confirmation envoyé',
    'inscription.validationCall': 'Appel de validation sous 24h',
    'inscription.platformAccess': 'Accès à la plateforme sous 48h',
    'inscription.formationStart': 'Début de formation selon planning',
    'inscription.error': 'Une erreur est survenue. Veuillez réessayer.',
    
    // Packs
    'pack.basic': 'Pack Basique',
    'pack.standard': 'Pack Standard',
    'pack.premium': 'Pack Premium',
    'pack.features': 'Fonctionnalités',
    'pack.whyChoose': 'Pourquoi choisir un pack ?',
    'pack.accelerated': 'Apprentissage accéléré',
    'pack.community': 'Communauté active',
    'pack.support': 'Support personnalisé',
    'pack.features.basic1': 'Accès aux cours en ligne',
    'pack.features.basic2': 'Support technique de base',
    'pack.features.basic3': 'Exercices pratiques',
    'pack.features.basic4': 'Certificat de participation',
    'pack.features.standard1': 'Tout du Pack Basique',
    'pack.features.standard2': 'Support prioritaire',
    'pack.features.standard3': 'Projets pratiques guidés',
    'pack.features.standard4': 'Sessions de mentorat (4h)',
    'pack.features.standard5': 'Accès à la communauté',
    'pack.features.standard6': 'Certificat accrédité',
    'pack.features.premium1': 'Tout du Pack Standard',
    'pack.features.premium2': 'Support illimité 24/7',
    'pack.features.premium3': 'Projets personnalisés',
    'pack.features.premium4': 'Mentorat individuel (12h)',
    'pack.features.premium5': 'Accès vie-time aux mises à jour',
    'pack.features.premium6': 'Préparation aux certifications',
    'pack.features.premium7': 'Accès aux recruteurs partenaires',
    'pack.features.premium8': 'Certificat premium',
    
    // Paiement
    'payment.method': 'Méthode de Paiement',
    'payment.card': 'Carte Bancaire',
    'payment.transfer': 'Virement Bancaire',
    'payment.onSite': 'Paiement sur Site',
    'payment.summary': 'Récapitulatif complet',
    'payment.formation': 'Formation',
    'payment.pack': 'Pack',
    'payment.duration': 'Durée',
    'payment.formationPrice': 'Prix formation',
    'payment.packSupplement': 'Supplément pack',
    'payment.total': 'Total',
    'payment.reference': 'Référence',
    'payment.date': 'Date',
    'payment.terms': 'Conditions générales',
    'payment.privacy': 'Politique de confidentialité',
    'payment.acceptTerms': 'J\'accepte les conditions générales et la politique de confidentialité',
    
    // Boutons
    'button.back': 'Retour à l\'accueil',
    'button.previous': 'Précédent',
    'button.next': 'Suivant',
    'button.finalize': 'Finaliser l\'Inscription',
    'button.processing': 'Traitement en cours...',
    'button.selected': 'Sélectionné',
    'button.select': 'Sélectionner',
    'button.backHome': 'Retour à l\'accueil',

    // Form fields
    'form.firstName': 'Prénom',
    'form.lastName': 'Nom',
    'form.email': 'Email',
    'form.phone': 'Téléphone',
    'form.address': 'Adresse',
    'form.city': 'Ville',
    'form.postalCode': 'Code Postal',
    'form.country': 'Pays',
    'form.company': 'Entreprise',
    'form.jobTitle': 'Poste Actuel',
    'form.experience': 'Expérience Professionnelle',
    'form.experience.select': 'Sélectionnez votre expérience',
    'form.experience.beginner': 'Débutant (0-2 ans)',
    'form.experience.intermediate': 'Intermédiaire (2-5 ans)',
    'form.experience.experienced': 'Expérimenté (5-10 ans)',
    'form.experience.expert': 'Expert (10+ ans)',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.formations': 'Training',
    'nav.pack': 'IoT Pack',
    'nav.contact': 'Contact',
    'nav.contactUs': 'Contact Us',
    
    // Hero
    'hero.badge': '🚀 Innovative Training in Advanced Technologies',
    'hero.title.ai': 'AI',
    'hero.title.iot': 'IoT',
    'hero.title.automates': 'Automation',
    'hero.title.master': 'Master ',
    'hero.title.and': ', ',
    'hero.title.andThe': 'and ',
    'hero.description': 'Smart Academy trains you in modern industrial technologies with practical and innovative approaches, combining online learning and in-person sessions.',
    'hero.cta.discover': 'Discover Our Training',
    'hero.cta.presentation': 'Watch Presentation',
    'hero.stats.students': 'Students Trained',
    'hero.stats.satisfaction': 'Satisfaction Rate',
    'hero.stats.domains': 'Areas of Expertise',
    
    // Formations
    'formations.title': 'Our Training Areas',
    'formations.subtitle': 'Practical and innovative training to master modern industrial technologies',
    'formations.ai.title': 'Artificial Intelligence',
    'formations.ai.description': 'Master machine learning algorithms, deep learning and practical AI applications in modern industry.',
    'formations.iot.title': 'Internet of Things (IoT)',
    'formations.iot.description': 'Develop complete IoT solutions, from sensor design to real-time data analysis.',
    'formations.automates.title': 'Programmable Logic Controllers',
    'formations.automates.description': 'Program and configure connected industrial controllers for advanced process automation.',
    'formations.learnMore': 'Learn More',
    'formations.hybrid.title': 'Hybrid Training',
    'formations.hybrid.description': 'Our training combines online learning and in-person sessions, with a strong focus on real projects and cutting-edge technology integration.',
    'formations.online': 'Online sessions',
    'formations.onlineDesc': 'Flexibility and accessibility',
    'formations.inPerson': 'In-person sessions',
    'formations.inPersonDesc': 'Hands-on practice and direct interaction',

    // Page Formations
    'formations.available': 'Available courses',
    'formations.totalHours': 'Total training hours',
    'formations.satisfaction': 'Satisfaction rate',
    'formations.popular': 'Popular',
    'formations.instructor': 'Instructor',
    'formations.features': 'What you\'ll learn',
    'formations.financing': 'Financing available',
    'formations.inscription': 'Enroll now',
    'formations.noFormations': 'No courses found',
    'formations.noFormationsDesc': 'No courses match your filtering criteria.',
    'formations.advantages': 'Why choose our courses?',
    'formations.certification': 'Recognized certification',
    'formations.certificationDesc': 'Internationally recognized industry certifications',
    'formations.support': 'Personalized support',
    'formations.supportDesc': 'Individualized coaching by our experts',
    'formations.flexible': 'Total flexibility',
    'formations.flexibleDesc': 'Online and in-person training according to your needs',
    'formations.projects': 'Practical projects',
    'formations.projectsDesc': 'Hands-on practice on real business cases',
    
    // Domaines
    'domains.all': 'All courses',
    'domains.ai': 'Artificial Intelligence',
    'domains.iot': 'Internet of Things',
    'domains.automation': 'Automation',
    
    // Pack IoT
    'pack.badge': 'Exclusive Pack',
    'pack.title': 'IoT Smart Starter Pack',
    'pack.subtitle': 'A complete set of tools and technologies to master industrial IoT, AI and programmable controllers in a connected environment.',
    'pack.features.title': 'Included Technologies',
    'pack.features.modules': 'Connected Modules',
    'pack.features.modulesDesc': 'Latest generation microcontrollers and sensors',
    'pack.features.ai': 'Integrated AI',
    'pack.features.aiDesc': 'Intelligent systems for predictive analysis',
    'pack.features.plc': 'Programmable Controllers',
    'pack.features.plcDesc': 'Connected and configurable industrial PLCs',
    'pack.features.connectivity': 'Advanced Connectivity',
    'pack.features.connectivityDesc': 'Wi-Fi, Bluetooth, LoRaWAN, 5G',
    'pack.features.security': 'Enhanced Security',
    'pack.features.securityDesc': 'Robust encryption and authentication',
    'pack.features.dev': 'Development Environment',
    'pack.features.devDesc': 'Complete IDE with integrated simulators',
    'pack.included.title': 'What\'s included',
    'pack.included.kit': 'Complete IoT development kit',
    'pack.included.aiModules': 'AI and machine learning modules',
    'pack.included.plc': 'Industrial programmable controllers',
    'pack.included.cloud': 'Dedicated cloud platform',
    'pack.included.docs': 'Complete technical documentation',
    'pack.included.support': '24/7 technical support',
    'pack.included.projects': 'Guided practical projects',
    'pack.included.certification': 'Official certification',
    'pack.price.complete': 'Complete Pack',
    'pack.cta.order': 'Order Now',
    'pack.guarantee': '30-day money-back guarantee',
    'pack.transform.title': 'Ready to transform your future?',
    'pack.transform.subtitle': 'Join professionals who already master tomorrow\'s technologies',
    'pack.cta.demo': 'Request a Demo',
    'pack.cta.brochure': 'Download Brochure',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Let\'s discuss your training needs and discover together how to integrate our solutions into your programs.',
    'contact.info.title': 'Contact Information',
    'contact.phone': 'Phone',
    'contact.phoneHours': 'Mon-Fri 9am-6pm',
    'contact.email': 'Email',
    'contact.emailResponse': 'Response within 24h',
    'contact.address': 'Address',
    'contact.addressNote': 'On-site training available',
    'contact.why.title': 'Why choose Smart Academy?',
    'contact.why.experts': 'Certified expert trainers',
    'contact.why.flexible': 'Flexible and adapted training',
    'contact.why.certification': 'Industry-recognized certification',
    'contact.form.title': 'Information Request',
    'contact.form.name': 'Full name',
    'contact.form.email': 'Email',
    'contact.form.company': 'Company / Organization',
    'contact.form.subject': 'Subject of interest',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.response': 'We commit to responding within 24 business hours.',
    
    // Footer
    'footer.description': 'Training center specialized in Artificial Intelligence, Internet of Things and connected programmable controllers. We train tomorrow\'s professionals in modern industrial technologies.',
    'footer.formations': 'Training',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.blog': 'Technical Blog',
    'footer.caseStudies': 'Case Studies',
    'footer.support': 'Support',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.website': 'Website',
    'footer.rights': 'All rights reserved.',

    // Inscription
    'inscription.title': 'Complete Your Registration',
    'inscription.subtitle': 'Complete your information to access your training',
    'inscription.step.personal': 'Personal Information',
    'inscription.step.professional': 'Professional Information',
    'inscription.step.pack': 'Choose Your Pack',
    'inscription.step.payment': 'Payment and Finalization',
    'inscription.success.title': 'Registration Confirmed!',
    'inscription.success.message': 'Congratulations! Your registration has been successfully recorded.',
    'inscription.withPack': ' with the ',
    'inscription.nextSteps': 'Next steps',
    'inscription.confirmationEmail': 'Confirmation email sent',
    'inscription.validationCall': 'Validation call within 24h',
    'inscription.platformAccess': 'Platform access within 48h',
    'inscription.formationStart': 'Training start according to schedule',
    'inscription.error': 'An error occurred. Please try again.',
    
    // Packs
    'pack.basic': 'Basic Pack',
    'pack.standard': 'Standard Pack',
    'pack.premium': 'Premium Pack',
    'pack.features': 'Features',
    'pack.whyChoose': 'Why choose a pack?',
    'pack.accelerated': 'Accelerated learning',
    'pack.community': 'Active community',
    'pack.support': 'Personalized support',
    'pack.features.basic1': 'Access to online courses',
    'pack.features.basic2': 'Basic technical support',
    'pack.features.basic3': 'Practical exercises',
    'pack.features.basic4': 'Participation certificate',
    'pack.features.standard1': 'Everything from Basic Pack',
    'pack.features.standard2': 'Priority support',
    'pack.features.standard3': 'Guided practical projects',
    'pack.features.standard4': 'Mentoring sessions (4h)',
    'pack.features.standard5': 'Community access',
    'pack.features.standard6': 'Accredited certificate',
    'pack.features.premium1': 'Everything from Standard Pack',
    'pack.features.premium2': '24/7 unlimited support',
    'pack.features.premium3': 'Customized projects',
    'pack.features.premium4': 'Individual mentoring (12h)',
    'pack.features.premium5': 'Lifetime access to updates',
    'pack.features.premium6': 'Certification preparation',
    'pack.features.premium7': 'Access to partner recruiters',
    'pack.features.premium8': 'Premium certificate',
    
    // Paiement
    'payment.method': 'Payment Method',
    'payment.card': 'Credit Card',
    'payment.transfer': 'Bank Transfer',
    'payment.onSite': 'Payment on Site',
    'payment.summary': 'Complete summary',
    'payment.formation': 'Training',
    'payment.pack': 'Pack',
    'payment.duration': 'Duration',
    'payment.formationPrice': 'Training price',
    'payment.packSupplement': 'Pack supplement',
    'payment.total': 'Total',
    'payment.reference': 'Reference',
    'payment.date': 'Date',
    'payment.terms': 'Terms and conditions',
    'payment.privacy': 'Privacy policy',
    'payment.acceptTerms': 'I accept the terms and conditions and the privacy policy',
    
    // Boutons
    'button.back': 'Back to home',
    'button.previous': 'Previous',
    'button.next': 'Next',
    'button.finalize': 'Finalize Registration',
    'button.processing': 'Processing...',
    'button.selected': 'Selected',
    'button.select': 'Select',
    'button.backHome': 'Back to home',

    // Form fields
    'form.firstName': 'First Name',
    'form.lastName': 'Last Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.address': 'Address',
    'form.city': 'City',
    'form.postalCode': 'Postal Code',
    'form.country': 'Country',
    'form.company': 'Company',
    'form.jobTitle': 'Current Position',
    'form.experience': 'Professional Experience',
    'form.experience.select': 'Select your experience',
    'form.experience.beginner': 'Beginner (0-2 years)',
    'form.experience.intermediate': 'Intermediate (2-5 years)',
    'form.experience.experienced': 'Experienced (5-10 years)',
    'form.experience.expert': 'Expert (10+ years)',
  },
  ar: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.formations': 'التدريب',
    'nav.pack': 'حزمة إنترنت الأشياء',
    'nav.contact': 'اتصل بنا',
    'nav.contactUs': 'اتصل بنا',
    
    // Hero
    'hero.badge': '🚀 تدريب مبتكر في التقنيات المتقدمة',
    'hero.title.ai': 'الذكاء الاصطناعي',
    'hero.title.iot': 'إنترنت الأشياء',
    'hero.title.automates': 'الأتمتة',
    'hero.title.master': 'أتقن ',
    'hero.title.and': '، ',
    'hero.title.andThe': 'و',
    'hero.description': 'تدربك الأكاديمية الذكية على التقنيات الصناعية الحديثة بأساليب عملية ومبتكرة، تجمع بين التعلم عبر الإنترنت والجلسات الحضورية.',
    'hero.cta.discover': 'اكتشف تدريباتنا',
    'hero.cta.presentation': 'شاهد العرض التقديمي',
    'hero.stats.students': 'طالب مدرب',
    'hero.stats.satisfaction': 'معدل الرضا',
    'hero.stats.domains': 'مجالات الخبرة',
    
    // Formations
    'formations.title': 'مجالات التدريب لدينا',
    'formations.subtitle': 'تدريب عملي ومبتكر لإتقان التقنيات الصناعية الحديثة',
    'formations.ai.title': 'الذكاء الاصطناعي',
    'formations.ai.description': 'أتقن خوارزميات التعلم الآلي والتعلم العميق وتطبيقات الذكاء الاصطناعي العملية في الصناعة الحديثة.',
    'formations.iot.title': 'إنترنت الأشياء',
    'formations.iot.description': 'طور حلول إنترنت الأشياء الكاملة، من تصميم أجهزة الاستشعار إلى تحليل البيانات في الوقت الفعلي.',
    'formations.automates.title': 'وحدات التحكم المنطقية القابلة للبرمجة',
    'formations.automates.description': 'برمج وكوّن وحدات التحكم الصناعية المتصلة للأتمتة المتقدمة للعمليات.',
    'formations.learnMore': 'اعرف المزيد',
    'formations.hybrid.title': 'التدريب المختلط',
    'formations.hybrid.description': 'يجمع تدريبنا بين التعلم عبر الإنترنت والجلسات الحضورية، مع التركيز القوي على المشاريع الحقيقية ودمج التقنيات المتطورة.',
    'formations.online': 'جلسات عبر الإنترنت',
    'formations.onlineDesc': 'مرونة وإمكانية الوصول',
    'formations.inPerson': 'جلسات حضورية',
    'formations.inPersonDesc': 'ممارسة عملية وتفاعل مباشر',

    // Page Formations
    'formations.available': 'التدريبات المتاحة',
    'formations.totalHours': 'ساعات التدريب',
    'formations.satisfaction': 'معدل الرضا',
    'formations.popular': 'شائع',
    'formations.instructor': 'المدرب',
    'formations.features': 'ما سوف تتعلمه',
    'formations.financing': 'تمويل متاح',
    'formations.inscription': 'سجل الآن',
    'formations.noFormations': 'لم يتم العثور على تدريبات',
    'formations.noFormationsDesc': 'لا توجد تدريبات تطابق معايير التصفية الخاصة بك.',
    'formations.advantages': 'لماذا تختار تدريباتنا؟',
    'formations.certification': 'شهادة معتمدة',
    'formations.certificationDesc': 'شهادات معترف بها دولياً في الصناعة',
    'formations.support': 'دعم مخصص',
    'formations.supportDesc': 'تدريب فردي من قبل خبرائنا',
    'formations.flexible': 'مرونة كاملة',
    'formations.flexibleDesc': 'تدريب عبر الإنترنت وحضوري حسب احتياجاتك',
    'formations.projects': 'مشاريع عملية',
    'formations.projectsDesc': 'تطبيق عملي على حالات عمل حقيقية',
    
    // Domaines
    'domains.all': 'جميع التدريبات',
    'domains.ai': 'الذكاء الاصطناعي',
    'domains.iot': 'إنترنت الأشياء',
    'domains.automation': 'الأتمتة',
    
    // Pack IoT
    'pack.badge': 'حزمة حصرية',
    'pack.title': 'حزمة البداية الذكية لإنترنت الأشياء',
    'pack.subtitle': 'مجموعة كاملة من الأدوات والتقنيات لإتقان إنترنت الأشياء الصناعي والذكاء الاصطناعي ووحدات التحكم القابلة للبرمجة في بيئة متصلة.',
    'pack.features.title': 'التقنيات المتضمنة',
    'pack.features.modules': 'وحدات متصلة',
    'pack.features.modulesDesc': 'متحكمات دقيقة وأجهزة استشعار من أحدث جيل',
    'pack.features.ai': 'ذكاء اصطناعي متكامل',
    'pack.features.aiDesc': 'أنظمة ذكية للتحليل التنبؤي',
    'pack.features.plc': 'وحدات تحكم قابلة للبرمجة',
    'pack.features.plcDesc': 'وحدات تحكم صناعية متصلة وقابلة للتكوين',
    'pack.features.connectivity': 'اتصال متقدم',
    'pack.features.connectivityDesc': 'واي فاي، بلوتوث، LoRaWAN، 5G',
    'pack.features.security': 'أمان معزز',
    'pack.features.securityDesc': 'تشفير ومصادقة قوية',
    'pack.features.dev': 'بيئة التطوير',
    'pack.features.devDesc': 'IDE كامل مع محاكيات متكاملة',
    'pack.included.title': 'ما هو مشمول',
    'pack.included.kit': 'مجموعة تطوير إنترنت الأشياء الكاملة',
    'pack.included.aiModules': 'وحدات الذكاء الاصطناعي والتعلم الآلي',
    'pack.included.plc': 'وحدات التحكم الصناعية القابلة للبرمجة',
    'pack.included.cloud': 'منصة سحابية مخصصة',
    'pack.included.docs': 'وثائق تقنية كاملة',
    'pack.included.support': 'دعم تقني 24/7',
    'pack.included.projects': 'مشاريع عملية موجهة',
    'pack.included.certification': 'شهادة رسمية',
    'pack.price.complete': 'الحزمة الكاملة',
    'pack.cta.order': 'اطلب الآن',
    'pack.guarantee': 'ضمان استرداد الأموال لمدة 30 يوماً',
    'pack.transform.title': 'مستعد لتحويل مستقبلك؟',
    'pack.transform.subtitle': 'انضم إلى المحترفين الذين يتقنون بالفعل تقنيات الغد',
    'pack.cta.demo': 'اطلب عرضاً توضيحياً',
    'pack.cta.brochure': 'تحميل الكتيب',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'دعنا نناقش احتياجاتك التدريبية ونكتشف معاً كيفية دمج حلولنا في برامجك.',
    'contact.info.title': 'معلومات الاتصال',
    'contact.phone': 'الهاتف',
    'contact.phoneHours': 'الإثنين-الجمعة 9ص-6م',
    'contact.email': 'البريد الإلكتروني',
    'contact.emailResponse': 'رد خلال 24 ساعة',
    'contact.address': 'العنوان',
    'contact.addressNote': 'التدريب في الموقع متاح',
    'contact.why.title': 'لماذا تختار الأكاديمية الذكية؟',
    'contact.why.experts': 'مدربون خبراء معتمدون',
    'contact.why.flexible': 'تدريب مرن ومتكيف',
    'contact.why.certification': 'شهادة معترف بها في الصناعة',
    'contact.form.title': 'طلب معلومات',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.company': 'الشركة / المؤسسة',
    'contact.form.subject': 'موضوع الاهتمام',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.response': 'نلتزم بالرد خلال 24 ساعة عمل.',
    
    // Footer
    'footer.description': 'مركز تدريب متخصص في الذكاء الاصطناعي وإنترنت الأشياء ووحدات التحكم القابلة للبرمجة المتصلة. نحن ندرب محترفي الغد في التقنيات الصناعية الحديثة.',
    'footer.formations': 'التدريب',
    'footer.resources': 'الموارد',
    'footer.documentation': 'الوثائق',
    'footer.blog': 'المدونة التقنية',
    'footer.caseStudies': 'دراسات الحالة',
    'footer.support': 'الدعم',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الاستخدام',
    'footer.website': 'الموقع الإلكتروني',
    'footer.rights': 'جميع الحقوق محفوظة.',

    // Inscription
    'inscription.title': 'أكمل تسجيلك',
    'inscription.subtitle': 'أكمل معلوماتك للوصول إلى تدريبك',
    'inscription.step.personal': 'المعلومات الشخصية',
    'inscription.step.professional': 'المعلومات المهنية',
    'inscription.step.pack': 'اختر حزمتك',
    'inscription.step.payment': 'الدفع والإنهاء',
    'inscription.success.title': 'تم تأكيد التسجيل!',
    'inscription.success.message': 'مبروك! تم تسجيلك بنجاح.',
    'inscription.withPack': ' مع ',
    'inscription.nextSteps': 'الخطوات القادمة',
    'inscription.confirmationEmail': 'تم إرسال بريد التأكيد',
    'inscription.validationCall': 'مكالمة تحقق خلال 24 ساعة',
    'inscription.platformAccess': 'الوصول للمنصة خلال 48 ساعة',
    'inscription.formationStart': 'بدء التدريب حسب الجدول',
    'inscription.error': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    
    // Packs
    'pack.basic': 'الحزمة الأساسية',
    'pack.standard': 'الحزمة القياسية',
    'pack.premium': 'الحزمة المميزة',
    'pack.features': 'الميزات',
    'pack.whyChoose': 'لماذا تختار حزمة؟',
    'pack.accelerated': 'تعلم مسرع',
    'pack.community': 'مجتمع نشط',
    'pack.support': 'دعم مخصص',
    'pack.features.basic1': 'الوصول إلى الدورات عبر الإنترنت',
    'pack.features.basic2': 'دعم فني أساسي',
    'pack.features.basic3': 'تمارين عملية',
    'pack.features.basic4': 'شهادة مشاركة',
    'pack.features.standard1': 'كل ما في الحزمة الأساسية',
    'pack.features.standard2': 'دعم ذو أولوية',
    'pack.features.standard3': 'مشاريع عملية موجهة',
    'pack.features.standard4': 'جلسات إرشاد (4 ساعات)',
    'pack.features.standard5': 'الوصول إلى المجتمع',
    'pack.features.standard6': 'شهادة معتمدة',
    'pack.features.premium1': 'كل ما في الحزمة القياسية',
    'pack.features.premium2': 'دعم غير محدود 24/7',
    'pack.features.premium3': 'مشاريع مخصصة',
    'pack.features.premium4': 'إرشاد فردي (12 ساعة)',
    'pack.features.premium5': 'وصول مدى الحياة للتحديثات',
    'pack.features.premium6': 'تحضير للشهادات',
    'pack.features.premium7': 'الوصول إلى جهات التوظيف الشريكة',
    'pack.features.premium8': 'شهادة مميزة',
    
    // Paiement
    'payment.method': 'طريقة الدفع',
    'payment.card': 'بطاقة ائتمان',
    'payment.transfer': 'تحويل بنكي',
    'payment.onSite': 'الدفع في الموقع',
    'payment.summary': 'ملخص كامل',
    'payment.formation': 'التدريب',
    'payment.pack': 'الحزمة',
    'payment.duration': 'المدة',
    'payment.formationPrice': 'سعر التدريب',
    'payment.packSupplement': 'تكلفة الحزمة الإضافية',
    'payment.total': 'المجموع',
    'payment.reference': 'المرجع',
    'payment.date': 'التاريخ',
    'payment.terms': 'الشروط والأحكام',
    'payment.privacy': 'سياسة الخصوصية',
    'payment.acceptTerms': 'أوافق على الشروط والأحكام وسياسة الخصوصية',
    
    // Boutons
    'button.back': 'العودة إلى الرئيسية',
    'button.previous': 'السابق',
    'button.next': 'التالي',
    'button.finalize': 'إنهاء التسجيل',
    'button.processing': 'جاري المعالجة...',
    'button.selected': 'محدد',
    'button.select': 'اختر',
    'button.backHome': 'العودة إلى الرئيسية',

    // Form fields
    'form.firstName': 'الاسم الأول',
    'form.lastName': 'الاسم الأخير',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'الهاتف',
    'form.address': 'العنوان',
    'form.city': 'المدينة',
    'form.postalCode': 'الرمز البريدي',
    'form.country': 'البلد',
    'form.company': 'الشركة',
    'form.jobTitle': 'المنصب الحالي',
    'form.experience': 'الخبرة المهنية',
    'form.experience.select': 'اختر خبرتك',
    'form.experience.beginner': 'مبتدئ (0-2 سنة)',
    'form.experience.intermediate': 'متوسط (2-5 سنوات)',
    'form.experience.experienced': 'خبير (5-10 سنوات)',
    'form.experience.expert': 'خبير جداً (10+ سنوات)',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};